### ISSUE TITLE
Can you make it scrap other details too

### ISSUE THREAD

**Issue by VikasRana** [cromize/beatport_tracktagger#3]
It doesn't scrap Beats-Per-Minute (BPM) and Catalog. Can this be scraped too?

**Comment by cromize** [comment]
BPM assignment is fixed in master. Catalog number could be scraped, but into what tag should it be put? If you mean Traktor's catalog number tag field, then it could be done, but it's Traktor custom thing.

**Comment by VikasRana** [comment]
Thanks for the BPM.

You are right, I guess Catalog cannot be saved under proper tag in the tracks.

**Comment by VikasRana** [comment]
Been trying to tag this file: 

https://www.beatport.com/track/waiting-original-mix/13174788

But its taking tags from somewhere else despite naming the file as 13174788_track.mp3
https://app.box.com/s/8wph9sw7k1cjxwx585701mdgs6ft2o7o

Please take a look.

**Comment by cromize** [comment]
I tried to tag your file, and it tagged well. Try to remove local.db and sync again.

Coming back to the catalog number, it could be put into some tag field. At worst in comments section. Depends on what you need.

**Comment by VikasRana** [comment]
Catalog can be put along with album name  too. Like: Some Album (Catalog)

tried deleting local.db - still the same result.

Can you try one more time with this file - https://app.box.com/s/nldggm47cspjfabji25pt8l08lz75dhn

it should fetch data from this track - https://www.beatport.com/track/eternal-original-mix/13193677

but it fetches data from here - https://www.beatport.com/track/legion-original-mix/4669257

I'm doing : python.exe tracktagger.py -z -ft -i xxxx.mp3
this mp3 contains the least data possible - only artist and album name pre-tagged.

Wondering what am I doing wrong.

**Comment by cromize** [comment]
Oh, I see the issue. You didn't mention that you run it in fuzzy mode. I will fix it tonight.

If you have specific pattern for naming your files, it could take the name and artist from that. Instead of having to manually rewrite each track's artist and track name field.

**Comment by cromize** [comment]
Fuzzy track query results should be more accurate now. Could you test more tracks on it?

**Comment by VikasRana** [comment]
I tested some more tracks only once it failed to query accurately. Nicely done rest of the times. Tested like with 50 tracks.

Can you expalin the difference in Fuzzy searching and Regular searching? And which one is better?

**Comment by VikasRana** [comment]
This is the track that had problem: https://app.box.com/s/99u3120z5p6hln93c1a915ghizmp0846

**Comment by cromize** [comment]
The problem with that track is Beatport having multiple releases of that. It just picked the oldest one, which happens to be the single one release. There is not much you can do, except to specify the release before tagging.

Or maybe it could compare the included artwork with the specific release on Beatport, if that artwork is included in the mp3 file, but I think this problem is a corner case.

About the fuzzy searching, it's a way to search strings approximately, with probabilities. This helps with mistakes or variations in text, as it won't deny name string which has some bad character in it.

Tagger basically concatenates the artist, track name and remixer into string and puts it into Beatport query. After that, the result is fuzzy searched for the best match.
